version: "3"
services:
  vue:
    image: node:lts-alpine
    build:
      context: ./view
      dockerfile: Dockerfile
    container_name: vue_container
    ports:
      - "8081:8081"
    volumes:
      #node_moduleを入れるボリューム
      - /app/view/node_modules
      #コンテナ内の指定ディレクトリをホスト側と同期
      - .:/app/
    #-it
    stdin_open: true
    tty: true
  app:
    build:
      context: .
    image: golang:1.16.7
    container_name: go_container
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/optim_22_app/
    tty: true
    stdin_open: true
    command: /bin/sh
  db:
    build:
      context: ./mysql
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: optim_dev
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 13306:3306
