version: '3'
services:
  app:
    build:
      context: .
    image: golang:1.16.7
    container_name: go_container
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
  db:
    build:
      context: ./mysql
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: rootpass
    ports:
      - 13306:3306